---
image: python:3-alpine

stages:
  - test

test:
  stage: test
  artifacts:
    paths:
      - htmlcov
  script: |
    python setup.py install
    pip install flake8==3.5.0 coverage pytest mock
    flake8
    coverage erase
    coverage run -p -m pytest
    coverage combine
    coverage report --omit='tests/*'
    coverage html --omit='tests/*'
    coverage report -m --omit 'tests/*'
